### ISSUE TITLE
How to use plugin in swarm mode

### ISSUE THREAD

**Issue by metalicjames** [hjdr4/docker-volume-glusterfs#3]
In regular non-swarm mode I can start and use a container with a glusterfs volume using this plugin. However in swarm/service mode, the container always fails to start. Having created a volume called "test" which is confirmed to work in non-swarm mode, the following fails to start:
```
   sudo docker service create \
   --name test \
   --mount type=volume,volume-driver=hjdr4plugins/docker-volume-glusterfs,src=test,dst=/test \    
   ubuntu:16.04 \
   /bin/bash
```

With error message on container creation: 
```
    Error grabbing logs: EOF
```

What am I doing wrong?

**Comment by hjdr4** [comment]
Hello,

Can you provide the output of `docker volume ls`  in working/non-working situations ?
You should have something like `hjdr4plugins/docker-volume-glusterfs:latest   test`

**Comment by metalicjames** [comment]
Hmm, yes I see that there now. It seems my actual frustration is that I can create services with the volume attached from the CLI, but from docker-compose files I cannot figure out the correct way to do it. 

e.g.
```
version: "3.2"
services:

  vertcoind:
    image: lukechilds/vertcoind
    volumes:
      - vertcoind_data:/data
    command: -rpcuser=middleware -rpcpassword=middleware -txindex

  vtc-middleware-cpp:
    image: jamesl22/vtc-middleware-cpp
    volumes:
      - vertcoind_data:/data
      - index:/tmp/tempdb
      
volumes:
  vertcoind_data:
    driver: hjdr4plugins/docker-volume-glusterfs
  index:
```
